name: routes_example
version: 0.0.1
author: Matthew Butler
description: A sample Polymer application using routes.
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: '>=0.9.0 <0.10.0'
  polymer: '>=0.9.0 <0.10.0'
  route: '>=0.4.6'
