name: routes_example
version: 0.0.1
author: Matthew Butler
description: A sample Polymer application using routes.
environment:
  sdk: '>=0.8.7'
dependencies:
  browser: any
  polymer: '>=0.8.7'
  route: any
